var money = require('./money_style');
module.exports = {
    current_price: money,
    market_cap: money,
    total_volume: money,
    high_24h: money,
    low_24h: money,
    price_change_24h: { type: Number, default: 0 },
    price_change_percentage_24h: { type: Number, default: 0 },
    price_change_percentage_7d: { type: Number, default: 0 },
    price_change_percentage_14d: { type: Number, default: 0 },
    price_change_percentage_30d: { type: Number, default: 0 },
    price_change_percentage_60d: { type: Number, default: 0 },
    price_change_percentage_200d: { type: Number, default: 0 },
    price_change_percentage_1y: { type: Number, default: 0 },
    market_cap_change_24h: { type: Number, default: 0 },
    market_cap_change_percentage_24h: { type: Number, default: 0 },
    price_change_24h_in_currency: money,
    price_change_percentage_1h_in_currency: money,
    price_change_percentage_24h_in_currency: money,
    price_change_percentage_7d_in_currency: money,
    price_change_percentage_14d_in_currency: money,
    price_change_percentage_30d_in_currency: money,
    price_change_percentage_60d_in_currency: money,
    price_change_percentage_200d_in_currency: money,
    price_change_percentage_1y_in_currency: money,
    market_cap_change_24h_in_currency: money,
    market_cap_change_percentage_24h_in_currency: money
  }